# SYMLINK: ~/.config/mise/config.toml

[tools] # Runtimes & Languages
usage = "latest"
# Java
java = "openjdk-25"
# Golang
go = "latest"
"go:github.com/pressly/goose/v3/cmd/goose" = "latest"
# Python 
python = { version = "latest", postinstall = "pip install pipx" }
"aqua:astral-sh/uv" = "latest"
# Javascript
node = "latest"
npm = "latest"
# Rust
rust = "latest"
# C/C++
make = "latest"
cmake = "latest"

# Editor
"aqua:neovim/neovim" = "latest"

# CLI Tools
"aqua:cli/cli" = "latest"
"aqua:BurntSushi/ripgrep" = "latest"
"aqua:ajeetdsouza/zoxide" = "latest"
"aqua:atuinsh/atuin" = "latest"
"aqua:starship/starship" = "latest"
"aqua:sxyazi/yazi" = "latest"
"aqua:mikefarah/yq" = "latest"
"aqua:jqlang/jq" = "latest"
"aqua:sharkdp/bat" = "latest"
"aqua:tmux/tmux-builds" = "latest"
"aqua:junegunn/fzf" = "latest"
"aqua:sharkdp/fd" = "latest"
"aqua:eza-community/eza" = "latest"
"aqua:docker/cli" = "latest"
"aqua:jesseduffield/lazydocker" = "latest"

[settings]
# Automatically sets JAVA_HOME whenever a Java version is active
legacy_version_file = true
# Automatically install missing tools needed when running `mise x`
auto_install = true
# Automatically choose the correct color theme for displaying mise output
color_theme = "auto"
# Another version of auto_install
not_found_auto_install = true
# Automatically sets GOROOT and adds GOPATH/bin to PATH
go.set_goroot = true
go.set_gopath = true

[tasks.setup]
run = """
set -e
if command -v dnf >/dev/null; then PM="sudo dnf install -y"
elif command -v apt >/dev/null; then PM="sudo apt install -y"
elif command -v brew >/dev/null; then PM="brew install"
else echo "No supported package manager found" && exit 1
fi
$PM unzip gcc make tar curl xclip tree git pkg-config
npm install -g tree-sitter-cli
pip install pylatexenc
"""
